### ISSUE TITLE
as_array() method for OpusFile is not available 

### ISSUE THREAD

**Issue by ivan339339** [TeamPyOgg/PyOgg#86]
Hi!

I create OpusFile instance like this:
```
import pyogg

opus_file = pyogg.OpusFile('file.opus')
```
But call `opus_file.as_array()` throws this exception:
```
AttributeError: 'OpusFile' object has no attribute 'as_array'
```

I work on Ubuntu 18.04, before steps above I installed `libopusfile-dev`.

Is this the expected behavior?

**Comment by mattgwwalker** [comment]
Did you install PyOgg using pip? If so, the latest version is only
available via the GitHub repository. I would recommend you install that
version instead, which may resolve your issue.

Cheers,

Matthew

**Comment by ivan339339** [comment]
Yes, I installed PyOgg using pip. 
Thank you for clarification.

**Comment by 562245918** [comment]
same question ,i install lastest version *.whl,and pip install  *.whl  ,But call opus_file.as_array() throws this exception:

AttributeError: 'OpusFile' object has no attribute as_array()

**Comment by 562245918** [comment]
@mattgwwalker

**Comment by Zuzu-Typ** [comment]
Hi @562245918 

Please try installing the latest version using `pip install git+https://github.com/TeamPyOgg/PyOgg.git`.
That way you install PyOgg directly from the master branch.

Cheers
--Zuzu_Typ--

**Comment by 562245918** [comment]
@Zuzu-Typ Thank you very much,it's OK.Please forgive me ..a beginner.
